## 第一題

題目說明：   
給定一個矩陣m，裡面的值都大於0。   
請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。   

```{python}
m = np.array([[0,1,10],[2,6,7]])
```

### Hint：
* 使用巢狀迴圈(nested loop)加判斷式

In [70]:
import numpy as np

In [71]:
m = np.array([[0, 1, 10], [2, 6, 7]])

In [83]:
m

array([[ 0,  1, 10],
       [ 2,  6,  7]])

In [73]:
m[1]

array([2, 6, 7])

In [88]:
def trans(matrix):
    # 建立一個0矩陣來存放
    keep_matrix = np.zeros(shape=(2,3))
    
    # nested loop
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if matrix[i][j] >= 1:
                keep_matrix[i][j] = 1
            else:
                keep_matrix[i][j] = 0
    
    return keep_matrix

In [89]:
trans(m)

array([[ 0.,  1.,  1.],
       [ 1.,  1.,  1.]])

## 第二題

題目說明：  
有A，B，C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績   

請隨機產生3個班級的成績單，每班10人，共5科   
weights=[0.25,0.25,0.25,0.15,0.10]   
請算出班級加權平均成績，並以一個array輸出

In [1]:
import numpy as np

In [5]:
class_a = np.random.randint(0, 101, size=(10,5))

In [7]:
# 查看class_a
# 10 students , 5 subject
class_a

array([[ 99,  30,  74,  39,  37],
       [ 65,  70,   4,  62,  49],
       [ 97,  30,  91,  21,  74],
       [ 84, 100,   7,  13,  33],
       [ 87,  61,  66,  18,  82],
       [ 60,  55,  48,  23,  24],
       [ 48,  13,  55,  39,  71],
       [ 31,  59,  97,  57,  10],
       [ 73,  70,   9,  82,  73],
       [ 95,  37,  79,  92,  95]])

In [8]:
class_b = np.random.randint(0, 101, size=(10,5))
class_c = np.random.randint(0, 101, size=(10,5))

In [94]:
def cal_score(class_score):
    weights = np.array([0.25, 0.25, 0.25, 0.15, 0.10])
    
    # 每位同學的加權分數
    # array
    score = np.dot(class_score, weights)
    
    # 一個班級的平均成績
    # float
    average = np.mean(score)
    
    #班級平均四捨五入
    return (score, np.around(average,))

In [95]:
cal_score(class_a)

(array([ 60.3 ,  48.95,  65.05,  53.  ,  64.4 ,  46.6 ,  41.95,  56.3 ,
         57.6 ,  76.05]), 57.0)

In [96]:
cal_score(class_b)

(array([ 59.4 ,  50.9 ,  36.15,  45.6 ,  49.9 ,  48.7 ,  65.85,  65.35,
         21.35,  58.05]), 50.0)

In [97]:
cal_score(class_c)

(array([ 58.7 ,  71.3 ,  52.15,  35.1 ,  51.8 ,  42.6 ,  47.9 ,  29.05,
         19.  ,  66.05]), 47.0)

## 挑戰題一

題目說明：   
請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array   
表示3個班級中30位學生的成績(小考，期中考，期末考)   
目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績  

成績計算方式如下：
1. 小考20%，期中考35%，期末考45%   
2. 期中考40%，期末考60%   
擇優作為學期成績

### Hint：
* 可以用雙重for迴圈 分別跑過班級跟人
* 可以先設一個array裝算出來的成績
* 記得要用return
* 請做個測試，檢驗你的結果，方便同學評分


In [98]:
import numpy as np

In [99]:
class_score = np.random.randint(0, 101, size=(3,30,3))

In [107]:
def cal_grade(scores):
    # 儲存最後的輸出
    result_score = np.zeros(shape=(3,30,1))
    
    
    # 先取出每個每個班級
    # class number -> 0,1,2
    for class_number in range(scores.shape[0]):
        
        # 取出每個學生
        # student -> 0,1,2,....,29
        for student in range(scores.shape[1]):
            quiz    = scores[class_number][student][0]
            midterm = scores[class_number][student][1]
            final   = scores[class_number][student][2]
            
            formula_1 = quiz*0.2 + midterm*0.35 + final*0.45
            formula_2 = midterm*0.4 + final*0.6
            
            if formula_1 > formula_2:
                result_score[class_number][student] = formula_1
            else:
                result_score[class_number][student] = formula_2
                
    return result_score

In [108]:
cal_grade(class_score)

array([[[ 51.6 ],
        [ 68.6 ],
        [ 60.  ],
        [ 56.  ],
        [ 31.65],
        [ 81.95],
        [ 37.6 ],
        [ 51.85],
        [ 72.6 ],
        [ 35.  ],
        [ 53.8 ],
        [ 32.  ],
        [ 25.8 ],
        [ 29.2 ],
        [ 72.4 ],
        [ 68.8 ],
        [ 45.4 ],
        [ 76.2 ],
        [ 16.6 ],
        [ 69.  ],
        [ 40.55],
        [ 17.8 ],
        [ 21.3 ],
        [ 49.85],
        [ 45.  ],
        [ 71.2 ],
        [ 32.25],
        [ 43.  ],
        [ 74.4 ],
        [ 55.2 ]],

       [[ 87.6 ],
        [ 75.6 ],
        [ 38.3 ],
        [ 34.6 ],
        [ 99.2 ],
        [ 71.  ],
        [ 57.45],
        [ 59.15],
        [ 18.45],
        [ 35.45],
        [ 57.55],
        [ 35.8 ],
        [ 57.6 ],
        [ 41.05],
        [ 84.  ],
        [ 19.95],
        [ 63.35],
        [ 39.4 ],
        [ 74.2 ],
        [ 20.75],
        [ 49.55],
        [ 53.4 ],
        [ 74.4 ],
        [ 18.4 ],
        [ 61.  ],
        

In [109]:
# 檢驗一個班的成績
def test(a_class_score):
    
    weight_1 = np.array([0.20, 0.35, 0.45])
    weight_2 = np.array([0   , 0.40, 0.60])
    
    formula_1 = np.dot(a_class_score, weight_1)
    formula_2 = np.dot(a_class_score, weight_2)
    
    result = np.where(formula_1>formula_2, formula_1, formula_2)
    
    return result

In [113]:
class_1 = class_score[0]
test(class_1)

array([ 51.6 ,  68.6 ,  60.  ,  56.  ,  31.65,  81.95,  37.6 ,  51.85,
        72.6 ,  35.  ,  53.8 ,  32.  ,  25.8 ,  29.2 ,  72.4 ,  68.8 ,
        45.4 ,  76.2 ,  16.6 ,  69.  ,  40.55,  17.8 ,  21.3 ,  49.85,
        45.  ,  71.2 ,  32.25,  43.  ,  74.4 ,  55.2 ])